import mysql.connector

def em(val):
    if val == None:
        return ''
    return val

lgc_5_mysql_settings = {
    'host':'localhost',
    'user':'lgc',
    'passwd':'zqooe872Fjdhe',
    'database':'lgc_v5',
}

lgc_4_1_mysql_settings = {
    'host':'localhost',
    'user':'',
    'passwd':'',
    'database':'lgc_4_1',
}

def lgc_4_1_connect():
    return mysql.connector.connect(
        host=lgc_4_1_mysql_settings['host'],
        user=lgc_4_1_mysql_settings['user'],
        passwd=lgc_4_1_mysql_settings['passwd'],
        database=lgc_4_1_mysql_settings['database'],
    )

def lgc_5_connect():
    return mysql.connector.connect(
        host=lgc_5_mysql_settings['host'],
        user=lgc_5_mysql_settings['user'],
        passwd=lgc_5_mysql_settings['passwd'],
        database=lgc_5_mysql_settings['database'],
    )

client_country_mapping = {
    'united states of america':'US',
    'états unis':'US',
    'etats unis ':'US',
    "france":'FR',
    "france ":'FR',
    'paris':'FR',
    "usa":'US',
    "inde":'IN',
    "etats unis":'US',
    "australie":'AU',
    "japan":'JP',
    "japon":'JP',
    "uk":'UK',
    "canada":'CA',
    "canada ":'CA',
    " canada ":'CA',
    "canada":'CA',
    "espagne":'ES',
    "russie":'RU',
    "australia":'AU',
    "brazil":'BR',
    "bresil":'BR',
    "mexique":'MX',
    "england":'UK',
    "united kingdom   ":'UK',
    "royaume uni":'UK',
    "royaume uni ":'UK',
    "espana":'ES',
    "italie":'IT',
    "japon":'JP',
    "paris":'FR',
    "chine":'CN',
    "suisse":'CH',
    "india":'IN',
    "india":'IN',
    "south africa":'ZA',
    "ca":'CA',
    "united kingdom":'UK',
    "united kingdom":'UK',
    "the netherlands":'NL',
    "netherlands":'NL',
    "pays bas":'NL',
    "pays bas":'NL',
    "angleterre":'UK',
    "lebanon":'LB',
    "republic of belarus":'BY',
    "united arab emirates":'AE',
    "thailand":'TH',
    "ksa":'SA',
    "italy":'IT',
    "italy":'IT',
    " canada":'CA',
    "luxembourg":'LU',
    "corée":'KR',
    " france":'FR',
    "france":'FR',
    "liban":'LB',
    "germany":'DE',
    "arabie saoudite":'SA',
    "arabie saoudite ":'SA',
    "maroc":'MA',
    "maroc":'MA',
    "brunei":'BN',
    "armenie":'AM',
    " usa":'US',
    "singapore":'SG',
    "singapore ":'SG',
    "emirats arabes unis":'AE',
    "philippines":'PH',
    "brésil":'BR',
    "italia":'IT',
    "rsa":'ZA',
    "ireland":'IE',
    "kingdom of bahrain":'BH',
    "united kongdom":'UK',
    "United Kindgdom":'UK',
    "united kindgdom":'UK',
    "china":'CN',
    "belgique":'BE',
    "deutschland":'DE',
    "afrique du sud":'ZA',
    "allemagne":'DE',
    "finlande":'FI',
    "quatar":'QA',
    "etats-unis":'US',
    "qatar":'QA',
    "turquie":'TR',
    "ca usa":'US',
    "états-unis d'amérique":'US',
    "kuwait":'KW',
    "us":'US',
    "macedoine":'MK',
    "taiwan":'TW',
    "egypte":'EG',
    "turkey":'TR',
    "pologne":'PL',
    "californie":'US',
    "british virgin islands":'VG',
    "martinique":'MQ',
    "tunisie":'TN',
    "singapour":'SG',
    "poland":'PL',
    "poland ":'PL',
    "cote d'ivoire":'CI',
    "cote ivoire":'CI',
    "great britain":'UK',
    "burkina faso":'BF',
    " pologne":'PL',
    "vénézuela":'VE',
    "hong kong":'HK',
    "republic of ireland":'IE',
    "israel":'IL',
    "la réunion":'RE',
    "belgium":'BE',
    "saudi arabia":'SA',
}
