from django.urls import path
from . import views
from . import billing_views

urlpatterns = [
    path('', views.home, name='lgc-home'),

    path('hr-create/', views.HRCreateView.as_view(), name='lgc-hr-create'),
    path('hr/<int:pk>/', views.HRUpdateView.as_view(), name='lgc-hr'),
    path('hr-account-list/', views.HRAccountListView.as_view(), name='lgc-hr-accounts'),
    path('hr-delete/<int:pk>', views.HRDeleteView.as_view(),
         name='lgc-hr-delete'),

    path('file-create/', views.PersonCreateView.as_view(),
         name='lgc-file-create'),
    path('file-list/', views.PersonListView.as_view(), name='lgc-files'),
    path('file-delete/<int:pk>', views.PersonDeleteView.as_view(),
         name='lgc-file-delete'),
    path('file/<int:pk>/', views.PersonUpdateView.as_view(), name='lgc-file'),
    path('file-search/ajax/', views.ajax_file_search_view,
         name='lgc-file-search-ajax'),

    path('account-create/', views.InitiateAccount.as_view(), name='lgc-account-create'),
    path('account-list/', views.Accounts.as_view(), name='lgc-accounts'),
    path('account/<int:pk>/', views.UpdateAccount.as_view(), name='lgc-account'),
    path('account-link/<int:pk>/', views.InitiateAccount.as_view(),
         name='lgc-account-link'),
    path('account-delete/<int:pk>', views.DeleteAccount.as_view(),
         name='lgc-account-delete'),

    path('insert-employee/', views.ajax_insert_employee_view,
         name='lgc-insert-employee'),
    path('process-create/', views.ProcessCreateView.as_view(),
         name='lgc-process-create'),
    path('process-list/', views.ProcessListView.as_view(),
         name='lgc-processes'),
    path('process-delete/<int:pk>', views.ProcessDeleteView.as_view(),
         name='lgc-process-delete'),
    path('process/<int:pk>/', views.ProcessUpdateView.as_view(),
         name='lgc-process'),
    path('process-search/ajax/', views.ajax_process_search_view,
         name='lgc-process-search-ajax'),

    path('process-stage-create/', views.ProcessStageCreateView.as_view(),
         name='lgc-process-stage-create'),
    path('process-stage-list/', views.ProcessStageListView.as_view(),
         name='lgc-process-stages'),
    path('process-stage-delete/<int:pk>',
         views.ProcessStageDeleteView.as_view(),
         name='lgc-process-stage-delete'),
    path('process-stage/<int:pk>/', views.ProcessStageUpdateView.as_view(),
         name='lgc-process-stage'),
    path('process-stage-search/ajax/', views.ajax_process_stage_search_view,
         name='lgc-process-stage-search-ajax'),

    path('person-process-list/<int:pk>/', views.PersonProcessListView.as_view(),
         name='lgc-person-processes'),
    path('person-process/<int:pk>/', views.PersonProcessUpdateView.as_view(),
         name='lgc-person-process'),
    path('person-process-search/ajax/<int:pk>', views.ajax_person_process_search_view,
         name='lgc-person-process-search-ajax'),

    path('download/<int:pk>/', views.download_file, name='lgc-download-file'),

    path('expirations/', views.expirations, name='lgc-expirations'),
    path('settings/', views.settings_view, name='lgc-settings'),

    path('client-create/', billing_views.ClientCreateView.as_view(),
         name='lgc-client-create'),
    path('client/<int:pk>/', billing_views.ClientUpdateView.as_view(),
         name='lgc-client'),
    path('clients/', billing_views.ClientListView.as_view(),
         name='lgc-clients'),
    path('client-delete/<int:pk>', billing_views.ClientDeleteView.as_view(),
         name='lgc-client-delete'),
    path('client-search/ajax/', billing_views.ajax_client_search_view,
         name='lgc-client-search-ajax'),

    path('invoice-create/', billing_views.InvoiceCreateView.as_view(),
         name='lgc-invoice-create'),
    path('invoice/<int:pk>/', billing_views.InvoiceUpdateView.as_view(),
         name='lgc-invoice'),
    path('invoices/', billing_views.InvoiceListView.as_view(),
         name='lgc-invoices'),
    path('quotations/', billing_views.QuotationListView.as_view(),
         name='lgc-quotations'),
    path('gen-invoice/<int:pk>', billing_views.generate_invoice_from_quote,
         name='lgc-gen-invoice'),
    path('invoice-delete/<int:pk>', billing_views.InvoiceDeleteView.as_view(),
         name='lgc-invoice-delete'),
    path('invoice-search/ajax/', billing_views.ajax_invoice_search_view,
         name='lgc-invoice-search-ajax'),
    path('quotation-search/ajax/', billing_views.ajax_quotation_search_view,
         name='lgc-quotation-search-ajax'),
    path('invoice-create/', billing_views.InvoiceCreateView.as_view(),
         name='lgc-invoice-create'),
    path('insert-client/', billing_views.invoice_insert_client,
         name='lgc-insert-client'),

    path('item-insert/', billing_views.InvoiceItemCreateView.as_view(),
         name='lgc-insert-item'),
    path('item-insert/<int:pk>/', billing_views.InvoiceItemUpdateView.as_view(),
         name='lgc-update-item'),
    path('item-delete/<int:pk>/', billing_views.invoice_item_delete_view,
         name='lgc-delete-item'),

    path('disbursement-insert/',
         billing_views.InvoiceDisbursementCreateView.as_view(),
         name='lgc-insert-disbursement'),
    path('disbursement-insert/<int:pk>/',
         billing_views.InvoiceDisbursementUpdateView.as_view(),
         name='lgc-update-disbursement'),
    path('disbursement-delete/<int:pk>/',
         billing_views.invoice_disbursement_delete_view,
         name='lgc-delete-disbursement'),

    path('billing-pdf/<int:pk>/',
         billing_views.billing_pdf_view, name='lgc-billing-pdf'),
    path('billing-csv/',
         billing_views.billing_csv_view, name='lgc-billing-csv'),
]
