"""
Django settings for lgc_base project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7g&a3%b538z5&#-4ud7q@eqnz!+lufnbgq1adk!ei#@0=o4a2j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["2.2.2.2", "localhost"]

# Application definition

INSTALLED_APPS = [
    'common.apps.CommonConfig',
    'users.apps.UsersConfig',
    'lgc.apps.LgcConfig',
    'hr.apps.HrConfig',
    'employee.apps.EmployeeConfig',
    'crispy_forms',
    'django_countries',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'djangoformsetjs',
    'bootstrap_datepicker_plus',
    'lgc.templatetags',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lgc.middleware.UserRolesCheck',
]

ROOT_URLCONF = 'lgc_base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lgc_base.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lgc_v5',
        'USER': 'lgc',
        'PASSWORD':'blah',
        'HOST':'/var/run/mysqld/mysqld.sock',
    }
}

AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/London'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = 'lgc-home'
LOGIN_URL = 'user-login'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

EMAIL_HOST = 'kw-net.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'autotestkw@example.com'
EMAIL_HOST_PASSWORD = 'udis82udD'
EMAIL_USE_TLS = True

SITE_URL = 'http://localhost:8000'
AUTH_TOKEN_EXPIRY = 48
AUTH_PASSWORD_EXPIRY = 3 * 30

MEDIA_ROOT= '/home/partage/LGC-documents'
MEDIA_URL = '/docs/'
MAX_FILE_SIZE = 2 # in megabytes

EXPIRATIONS_NB_DAYS  = 90
